# Generated by Django 3.2.5 on 2021-07-13 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import server_remoto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imunobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imunobiologico', models.CharField(max_length=30)),
                ('doses', models.IntegerField()),
                ('dias_prox_dose', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', server_remoto.models.EmptyStringToNoneField(blank=True, default=None, max_length=11, null=True, unique=True)),
                ('CNS', server_remoto.models.EmptyStringToNoneField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nomeMae', models.CharField(max_length=100)),
                ('nomeSocial', models.CharField(blank=True, max_length=100)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO'), ('IGNORADO', 'IGNORADO')], max_length=10)),
                ('raca', models.CharField(choices=[('AMARELA', 'AMARELA'), ('BRANCA', 'BRANCA'), ('INDIGENA', 'INDIGENA'), ('NAO INFORMADA', 'NAO INFORMADA'), ('PARDA', 'PARDA'), ('PRETA', 'PRETA')], max_length=20)),
                ('telefone', models.IntegerField()),
                ('gestante', models.BooleanField()),
                ('puerpera', models.BooleanField()),
                ('pais', models.CharField(max_length=100)),
                ('UF', models.CharField(choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('zona', models.CharField(choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], max_length=6)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perdas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('falha_equip', models.IntegerField()),
                ('falha_trans', models.IntegerField()),
                ('falta_energ', models.IntegerField()),
                ('frasc_trans', models.IntegerField()),
                ('imunobiologico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_remoto.imunobiologico', verbose_name='Imunobiológico')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('validade', models.DateField(null=True, verbose_name='Data de Validade do Lote')),
                ('imunobiologico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_remoto.imunobiologico', verbose_name='Imunobiológico')),
            ],
        ),
        migrations.CreateModel(
            name='Imunizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidades', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CIRROSE HEPATICA', 'CIRROSE HEPATICA'), ('DIABETES MELLITUS', 'DIABETES MELLITUS'), ('DOENCA NEUROLOGICA CRONICA', 'DOENCA NEUROLOGICA CRONICA'), ('DOENCA RENAL CRONICA', 'DOENCA RENAL CRONICA'), ('DOENCAS CARDIOVASCULARES E CEREBROVASCULARES', 'DOENCAS CARDIOVASCULARES E CEREBROVASCULARES'), ('GESTANTE', 'GESTANTE'), ('HEMOGLOBINOPATIA GRAVE', 'HEMOGLOBINOPATIA GRAVE'), ('HIPERTENSAO', 'HIPERTENSAO'), ('IMUNOSSUPRIMIDO', 'IMUNOSSUPRIMIDO'), ('OBESIDADE GRAVE', 'OBESIDADE GRAVE'), ('PACIENTE ONCOLOGICO', 'PACIENTE ONCOLOGICO'), ('PESSOA VIVENDO COM HIV', 'PESSOA VIVENDO COM HIV'), ('PNEUMOPATIA CRONICA GRAVE', 'PNEUMOPATIA CRONICA GRAVE'), ('PUERPERA', 'PUERPERA'), ('SINDROME DE DOWN', 'SINDROME DE DOWN'), ('TERAPIA RENAL SUBSTITUTIVA/DIALISE', 'TERAPIA RENAL SUBSTITUTIVA/DIALISE'), ('TRANSPLANTADO DE ORGAO SOLIDO E MEDULA OSSEA', 'TRANSPLANTADO DE ORGAO SOLIDO E MEDULA OSSEA')], default=None, max_length=378, verbose_name='Comorbidades')),
                ('CRM_medico_resp', models.IntegerField(blank=True, default=None, null=True, verbose_name='CRM médico responsável')),
                ('num_BPC', models.IntegerField(blank=True, default=None, null=True, verbose_name='Número do BPC')),
                ('dose', models.CharField(choices=[('UNICA', 'UNICA'), ('1º DOSE', '1º DOSE'), ('2º DOSE', '2º DOSE')], max_length=16, verbose_name='Dose')),
                ('via_admn', models.CharField(choices=[('EV', 'ENDOVENOSA'), ('ID', 'INTRADERMICA'), ('IM', 'INTRAMUSCULAR'), ('O', 'ORAL'), ('SC', 'SUBCUTANEA')], max_length=20, verbose_name='Via de Administração')),
                ('local_admn', models.CharField(choices=[('DD', 'DELTOIDE DIREITO'), ('DE', 'DELTOIDE ESQUERDO'), ('G', 'GLUTEO'), ('FL', 'LOCAL DO FERIMENTO'), ('VLD', 'VASTO LATERAL DA COXA DIREITO'), ('VLE', 'VASTO LATERAL DA COXA ESQUERDA'), ('VGD', 'VENTROGLUTEO DIREITO'), ('VGE', 'VENTROGLUTEO ESQUERDO')], max_length=20, verbose_name='Local de Administração')),
                ('grupo', models.CharField(choices=[('AEROVIARIOS', 'AEROVIARIOS'), ('COMORBIDADE', 'COMORBIDADE'), ('ESTUDO CLINICO', 'ESTUDO CLINICO'), ('IDOSO', 'IDOSO'), ('IDOSO EM ILPI', 'IDOSO EM ILPI'), ('INDIGENAS', 'INDIGENAS'), ('METROVIARIOS/CPTM', 'METROVIARIOS/CPTM'), ('MOTORISTAS E COBRADORES DE ONIBUS', 'MOTORISTAS E COBRADORES DE ONIBUS'), ('PESSOA >= 18 ANOS PORTADORA DE DEFICIENCIA RESIDENTES EM RI', 'PESSOA >= 18 ANOS PORTADORA DE DEFICIENCIA RESIDENTES EM RI'), ('PESSOA COM DEFICIENCIA', 'PESSOA COM DEFICIENCIA'), ('PESSOA COM DEFICIENCIA PERMANENTE SEVERA', 'PESSOA COM DEFICIENCIA PERMANENTE SEVERA'), ('POPULACAO EM GERAL', 'POPULACAO EM GERAL'), ('POPULACAO EM SITUACAO DE RUA', 'POPULACAO EM SITUACAO DE RUA'), ('PORTUARIOS', 'PORTUARIOS'), ('QUILOMBOLA', 'QUILOMBOLA'), ('RIBEIRINHAS', 'RIBEIRINHAS'), ('TRABALHADOR DA EDUCACAO', 'TRABALHADOR DA EDUCACAO'), ('TRABALHADOR DA SEGURANCA PUBLICA', 'TRABALHADOR DA SEGURANCA PUBLICA'), ('TRABALHADOR DE SAUDE', 'TRABALHADOR DE SAUDE')], max_length=100, verbose_name='Grupo de Atendimento')),
                ('estrategia', models.CharField(choices=[('CAMPANHA INDISCRIMINADA', 'CAMPANHA INDISCRIMINADA')], max_length=100, verbose_name='Estratégia')),
                ('data_aplic', models.DateField(null=True, verbose_name='Data de Aplicação')),
                ('data_apraz', models.DateField(blank=True, null=True, verbose_name='Data de Aprazamento')),
                ('estado_1_dose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Primeira Dose')),
                ('pais_1_dose', models.CharField(blank=True, max_length=100, null=True, verbose_name='País Primeira Dose')),
                ('imunobiologico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='server_remoto.imunobiologico', verbose_name='Imunobiológico')),
                ('lote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_remoto.lote', verbose_name='Lote')),
                ('paciente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_remoto.paciente', verbose_name='Paciente')),
                ('vacinador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vacinador')),
            ],
        ),
    ]
