# Generated by Django 3.2.5 on 2021-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_remoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente',
            field=models.JSONField(),
        ),
    ]
