# Generated by Django 3.2.5 on 2021-07-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_remoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imunizacao',
            name='comorbidades',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Comorbidades'),
        ),
    ]
